jobs:
  steps:
    - name: slackthreads trigger
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GH_PAT}}
          repository: yonicd/slackthreads
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
