jobs:
  check:
    - name: Run Check
        run: |
            Rscript -e "install.packages('remotes')" \
                    -e "remotes::install_github('${{ github.event.client_payload.repository }}@${{ github.event.client_payload.sha }}', force = TRUE)" \
                    -e  "remotes::install_deps(dependencies = TRUE)" \
                    -e "remotes::install_cran('rcmdcheck')" \
                    -e "rcmdcheck::rcmdcheck(args = '${{ matrix.config.args }}', error_on = 'warning', check_dir = 'check')"
