on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: deploy-slides

jobs:
  deploy-slides:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1      
      - name: Install dependencies
        run: |
          install.packages(c('remotes','rmarkdown','showtext','fs'))
          remotes::install_github('yihui/xaringan')
          remotes::install_github('gadenbuie/xaringanExtra')
          remotes::install_github('gadenbuie/xaringanthemer')
        shell: Rscript {0}
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Build
        run: rmarkdown::render('index.Rmd', 'xaringan::moon_reader',output_file = 'index.html')
        shell: Rscript {0}
      - name: Commit files
        run: |
          Rscript -e "fs::dir_tree()"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build Slides" -a        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: pages 
          force: true        
