name: testing
on: push

jobs: 
  run:
    name: Add a text file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "123" > file.txt

      - uses: EndBug/add-and-commit@v5
        with:
          message: "Add the very useful text file"
          add: "*.txt --force"
          branch: pages
          author_name: github-actions
          author_email: github-actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
